<!--<script type="text/javascript">
google_ad_client = "ca-pub-6584462893044440";
/* togue */
google_ad_slot = "6005770001";
google_ad_width = 728;
google_ad_height = 90;
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>-->

<script type="text/javascript"><!--
google_ad_client = "ca-pub-6584462893044440";
/* toquecooks-sidebar */
google_ad_slot = "2516286400";
google_ad_width = 200;
google_ad_height = 200;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>